shelfio_web/shelfio/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('shelfio.views',

    # Common Pages
    url(r'^$', 'welcome.welcome', name='welcome'),
    url(r'^about/$', 'simple.about', name='about'),
    url(r'^faq/$', 'simple.faq', name='faq'),
    url(r'^search/$', 'simple.search', name='search'),
    url(r'^privacy/$', 'simple.privacy', name='privacy'),
    url(r'^bookmark/$', 'simple.bookmark', name='bookmark'),
    
    # Session/account management
    url(r'^password/change/$', auth_views.password_change, {'template_name': 'registration/password_change_form.html'}, name='auth_password_change'),
    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='auth_login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'registration/logout.html'}, name='auth_logout'),
    url(r'^register/$', 'user_management.process_register', name='process_register'),
    url(r'^password/change/$', auth_views.password_change, {'template_name': 'registration/password_change_form.html'}, name='auth_password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done, {'template_name': 'registration/password_change_done.html'},   name='auth_password_change_done'),
    url(r'^password/reset/$', auth_views.password_reset, {'template_name': 'registration/password_reset_form.html'}, name='auth_password_reset'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, {'template_name': 'registration/password_reset_confirm.html'}, name='auth_password_reset_confirm'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete, {'template_name': 'registration/password_reset_complete.html'}, name='auth_password_reset_complete'),
    url(r'^password/reset/done/$', auth_views.password_reset_done, {'template_name': 'registration/password_reset_done.html'}, name='auth_password_reset_done'),

    # Add item page
    url(r'^add-item/$', 'item.user_create', name='user_item_create'), # user can create new shelf on item page
    
    # User page
    url(r'^(?P<user_name>[a-zA-Z0-9\-]+)/$', 'user.user_home', name='user_home'),
    url(r'^(?P<user_name>[a-zA-Z0-9\-]+)/helpers/$', 'user.helpers', name='user_helpers'),
    
    #  Shelf page
    url(r'^(?P<url_user_name>[a-zA-Z0-9\-]+)/(?P<url_shelf_slug>[a-zA-Z0-9\-_]+)/$', 'shelf.user_shelf', name='user_shelf'),
    url(r'^(?P<url_user_name>[a-zA-Z0-9\-]+)/embed/(?P<url_shelf_slug>[a-zA-Z0-9\-_]+)/$', 'shelf.embed_shelf', name='embed_shelf'),
    
)
urlpatterns += staticfiles_urlpatterns()

shelfio_web/urls.py
from django.conf.urls import patterns, url, include

from django.contrib import admin

admin.autodiscover()

handler404 = 'shelfio.views.simple.not_found'

urlpatterns = patterns('',
    url(r'^api/v1/', include('shelfio.urls_api')),
    url(r'^', include('shelfio.urls')),
)

shelfio_web/shelfio/models.py
import random
import string
import hashlib

from shelfio import utils
from shelfio import indexer
from shelfio.fields import UUIDField

from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import TextInput
from django.template.defaultfilters import slugify
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save


FORMAT_CHOICES = (('book', 'Book'),
                            ('Video/Film', 'Video'),
                            ('Sound Recording', 'Music'),
                            ('webpage', 'Webpage'))

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    display_welcome = models.BooleanField(default=True)
    favorites_are_private = models.BooleanField(default=False)
    gravatar_enabled = models.BooleanField(default=False)
    
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        
        # We want an auth token for each user. Seems like a handy spot, so lets do that here.
        auth_token = AuthTokens(user=instance)
        auth_token.save()

post_save.connect(create_user_profile, sender=User)

class AuthTokens(models.Model):
    user = models.ForeignKey(User)
    token = UUIDField(auto=True)
    notes = models.CharField(max_length=400)
    is_active = models.BooleanField(default=True)

class Shelf(models.Model):
    user = models.ForeignKey(User)
    shelf_uuid = UUIDField(auto=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    description = models.CharField(max_length=1000)
    creation_date = models.DateTimeField(auto_now=True)
    is_private = models.BooleanField(default=False)
    
    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        slug = slugify(self.name)
        if Shelf.objects.filter(user=self.user, slug=slug).exclude(pk=self.pk).exists():
            raise ValidationError('You already have a shelf by that name.')
        else:
            self.slug = slugify(self.name)
            super(Shelf, self).save(*args, **kwargs)
            
        # We want items to be searchable through elastic search, pass the data off to our indexer
        if not self.is_private:
            indexer.index_shelf(self)
            
    def delete(self, *args, **kwargs):
        super(Shelf, self).delete(*args, **kwargs)
        indexer.unindex_shelf(self)
        #TODO: Delete items on the shelf if shelf is deleted 

class Item(models.Model):
    shelf = models.ForeignKey(Shelf)
    item_uuid = UUIDField(auto=True)
    title = models.CharField(max_length=200)
    link = models.URLField(max_length=2000)
    measurement_page_numeric = models.PositiveIntegerField(default=300)
    measurement_height_numeric = models.DecimalField(default='25.5', max_digits=5, decimal_places=2)
    format = models.CharField(max_length=200, default='book')
    shelfrank = models.PositiveIntegerField(default=random.randint(1, 99))
    creation_date = models.DateTimeField(auto_now=True)
    pub_date = models.PositiveIntegerField(default=utils.get_current_year())
    isbn = models.CharField(max_length=200, null=True, blank=True)
    notes = models.CharField(max_length=2000, null=True, blank=True)
    sort_order = models.PositiveIntegerField(editable=False) 

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.pk:
            try:
                max = Item.objects.order_by('-sort_order')[0].sort_order
                self.sort_order = max + 1
            except IndexError:
                self.sort_order = 1
        super(Item, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        super(Item, self).delete(*args, **kwargs)
        indexer.unindex_item(self)
        
    class Meta:
        ordering = ['-sort_order']
        models.CharField(max_length=200)   
    
class Creator(models.Model):
    item = models.ForeignKey(Item)
    creator_uuid = UUIDField(auto=True)
    name = models.CharField(max_length=200)
    
    def save(self, *args, **kwargs):
        super(Creator, self).save(*args, **kwargs)
    
        # We want items to be searchable through elastic search, pass the data off to our indexer
        if not self.item.shelf.is_private:
            indexer.index_item(self.item)

    
    def __unicode__(self):
        return self.name
    
class FavoriteUser(models.Model):
    """Users can favorite (or follow or star) another user"""
    
    favorite_user_uuid = UUIDField(auto=True)
    follower = models.ForeignKey(User, related_name='user_follower')
    leader = models.ForeignKey(User, related_name='user_leader    ')
    
    def save(self, *args, **kwargs):
        if FavoriteUser.objects.filter(follower=self.follower, leader=self.leader).exclude(pk=self.pk).exists():
            raise ValidationError('You have already favorited that user.')
        else:
            super(FavoriteUser, self).save(*args, **kwargs)
    
class FavoriteShelf(models.Model):
    """Users can favorite (or follow or star) a shelf"""
    
    favorite_shelf_uuid = UUIDField(auto=True)
    user = models.ForeignKey(User)
    shelf = models.ForeignKey(Shelf)
    
    def save(self, *args, **kwargs):
        if FavoriteShelf.objects.filter(user=self.user, shelf=self.shelf).exclude(pk=self.pk).exists():
            raise ValidationError('You have already favorited that shelf.')
        else:
            super(FavoriteShelf, self).save(*args, **kwargs)    

    
#Forms:
class AddToShelfConfirmForm(forms.Form):
    shelf = forms.ModelChoiceField(queryset=Shelf.objects.all())
    title = forms.CharField(max_length=300)
    author = forms.CharField(max_length=100)
    
class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput(render_value=False), max_length=100)
    
class UserRegForm(forms.ModelForm):
    """
    stripped down user reg form
    This is mostly a django.contrib.auth.forms.UserCreationForm
    """
    error_messages = {
        'duplicate_username': "A user with that username already exists.",
        'duplicate_email': "A user with that email address already exists.",
    }
    username = forms.RegexField(label="Username", max_length=30,
        regex=r'^[\w.@+-]+$',
        help_text = "30 characters or fewer. Letters, digits and "
                      "@/./+/-/_ only.",
        error_messages = {
            'invalid': "This value may contain only letters, numbers and "
                         "@/./+/-/_ characters."})
    
    email = forms.RegexField(label="Email", required=True, max_length=254,
        regex=r'^[\w.@+-]+$',
        help_text = "Letters, digits and @/./+/-/_ only. 254 characters or fewer.",
        error_messages = {
            'invalid': "This value may contain only letters, numbers and "
                         "@/./+/-/_ characters."})
    
    
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "email", "password")

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])
    
    def clean_email(self):
        # Since User.email is unique, this check is redundant,
        # but it sets a nicer error message than the ORM.
        
        email = self.cleaned_data["email"]
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError(self.error_messages['duplicate_email'])

    def save(self, commit=True):
        user = super(UserRegForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class EmailInput(TextInput):
    input_type = 'email'

class EditProfileForm(forms.Form):
    first_name = forms.CharField(max_length=100, required=False)
    last_name = forms.CharField(max_length=100, required=False)
    email = forms.EmailField(required=False, widget=EmailInput)

class NewShelfForm(forms.Form):
    name = forms.CharField(max_length=200)
    description = forms.CharField(
        max_length=1000,
        required=False,
        widget=forms.Textarea(attrs={'rows': '4'}),
    )
    is_private = forms.BooleanField(required=False)

class AddItemForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(AddItemForm, self).__init__(*args, **kwargs)
        if user is not None:
            self.fields['shelf'].queryset = Shelf.objects.filter(user=user)
            self.fields['shelf'].empty_label = None
    class Meta:
        model = Item
        widgets = { 'shelfrank' : forms.HiddenInput(),
                   'format' : forms.Select(choices=FORMAT_CHOICES),
                   'pub_date' : forms.TextInput(attrs={'size':4, 'maxlength':4}),
                   'notes': forms.Textarea(attrs={'rows': '4'}) }

class CreatorForm(forms.Form):
    creator = forms.CharField(max_length=1000)

shelfio_web/shelfio/views/item.py
import logging
import urllib
import json

from shelfio.utils import fill_with_get
from shelfio.models import Shelf, Creator, AddItemForm, CreatorForm
from shelfio.views.api.v1.item import serialize_item

from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, render_to_response
from django.contrib.auth.views import redirect_to_login
from django.contrib import messages
from django.core.context_processors import csrf
from django.http import HttpResponse
from django.core.serializers.json import DjangoJSONEncoder



logger = logging.getLogger(__name__)

def user_create(request):
    """When a user adds an item using the add item form. (The bookmarklet populates the add item form"""
        
    if not request.user.is_authenticated():
        messages.warning(request, 'You need to sign in to add items.')
        #return redirect(reverse('process_login'))
        return redirect_to_login(urllib.quote_plus(request.get_full_path()))
   
    context = {}
    context.update(csrf(request))
       
    if request.method == 'GET':
        
        add_item_form = AddItemForm(request.user)
        creator_form = CreatorForm()
        fill_with_get(add_item_form, request.GET)
        fill_with_get(creator_form, request.GET)

    elif request.method == 'POST':
        # A user can create a new shelf while adding an item      
        if 'new_shelf_name' in request.POST:
            new_shelf = Shelf(
                user=request.user,
                name = request.POST['new_shelf_name'],
                description = request.POST['new_shelf_description'],
                is_private = request.POST['new_shelf_is_private'],
            )
            try:
                new_shelf.save()
            except ValidationError:
                messages.error(request, 'A shelf with that name already exists.')
            return redirect(request.path)
        
        add_item_form = AddItemForm(request.user, request.POST)
        creator_form = CreatorForm(request.POST)
                
        if add_item_form.is_valid() and creator_form.is_valid():
            item = add_item_form.save()
            _save_creators(creator_form, item)

            success_text = '%(item)s added to %(shelf)s.' % {
                'item': add_item_form.cleaned_data['title'],
                'shelf': add_item_form.cleaned_data['shelf'].name
            }
            messages.success(request, success_text)
            return redirect(reverse(
                'user_shelf',
                args=[request.user.username, add_item_form.cleaned_data['shelf'].slug],
            ))

    context.update({
        'messages': messages.get_messages(request),
        'user': request.user,
        'add_item_form': add_item_form,
        'creator_form': creator_form
    })
    return render_to_response('item/create.html', context)

def add_item(request):
    if not request.user.is_authenticated():
        return HttpResponse(status=401)

    form = AddItemForm(request.user, request.POST)
    creator_form = CreatorForm(request.POST)
    if form.is_valid() and creator_form.is_valid():
        item = form.save()
        _save_creators(creator_form, item)
        return HttpResponse(json.dumps(serialize_item(item), cls=DjangoJSONEncoder), mimetype='application/json')
    else:
        return HttpResponse(status=400)


def _save_creators(creator_form, item):
    creators = [c.strip() for c in creator_form.cleaned_data['creator'].split(',')]
    for creator in creators:
        c = Creator(name=creator, item=item)
        c.save()

shelfio_web/shelfio/views/simple.py
from django.shortcuts import render_to_response


"""
If it's a simple view, let's put it here
"""

def not_found(request):
    """The application-wide 404 page."""
    return render_to_response('404.html', {'user': request.user})

def about(request):
    """The application-wide about page."""
    return render_to_response('about.html', {'user': request.user})

def privacy(request):
    """The application-wide privacy policy page."""
    return render_to_response('privacy.html', {'user': request.user})

def bookmark(request):
    """The application-wide bookmark page."""
    return render_to_response('bookmark.html', {'user': request.user})

def faq(request):
    """The application-wide FAQ page."""
    return render_to_response('faq.html', {'user': request.user})

def search(request):
    """The application-wide search page."""
    return render_to_response('search.html', {'user': request.user})

shelfio_web/shelfio/templates/partials/footer.html
<footer class="global-footer">
	<p><span class="branding"><img src="{{ STATIC_PREFIX }}images/liblabstamp.png" /><a href="http://librarylab.law.harvard.edu">A Harvard Library Innovation Lab Project</a></span> <a href="{% url 'about' %}">About</a> | <a href="{% url 'bookmark' %}">Shelf.io Bookmark</a> | <a href="{% url 'faq' %}">Common Questions</a> | <a href="{% url 'privacy' %}">Legal</a></p>
</footer>

shelfio_web/shelfio/templates/partials/header.html
<header class="global-header">
	<nav>
		<h1>
			<a href="{% url 'welcome' %}">Shelf.io</a>
		</h1>
		<ul>
		  <li><form id="search-form" action="{% url 'search' %}" method="get">
		    <input type="hidden" name="type" value="item">
			  <input placeholder="search" name="q">
			  <button class="button header-icon-search" type="submit"></button>
			</form>
			{% if user.is_authenticated %}
				<li><a class="icon-user" href="{% url 'welcome' %}{{ user.username }}">{{ user.username }}</a></li>
				<li><a class="icon-logout" href="{% url 'auth_logout' %}">Logout</a></li>
			{% else %}
				<li><a class="icon-login" href="{% url 'auth_login' %}">Login</a></li>
				<li><a class="icon-register" href="{% url 'process_register' %}">Register</a></li>
			{% endif %}
		</ul>
	</nav>
</header>

{% include "partials/messages.html" %}

shelfio_web/shelfio/templates/partials/messages.html
{% if messages %}
	<ul class="flash-messages">
		{% for message in messages %}
			<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
		{% endfor %}
	</ul>
{% endif %}

shelfio_web/shelfio/templates/partials/new-shelf-form.html
<form action="{% url 'user_home' user.username %}" method="post" class="modal island contained-form" id="new-shelf">
	{% csrf_token %}
	<header>
		<h3>New Shelf</h3>
	</header>

	{{ new_shelf_form.non_field_errors }}
	<section>
		<p>
			{{ new_shelf_form.name.errors }}
			<label for="id_name">Shelf Name <span id="input_preview"></span></label>
			{{ new_shelf_form.name }}
		</p>
		<p>
			{{ new_shelf_form.description.errors }}
			<label for="id_description">Shelf Description</label>
			{{ new_shelf_form.description }}
		</p>
		<p>
			{{ new_shelf_form.is_private.errors }}
			<label>Make shelf private {{ new_shelf_form.is_private }}</label>
		</p>

		<p>
		  <a class="button neutral modal-close">Cancel</a>
			<button type="submit" class="button positive icon-ok">Create Shelf</button>
		</p>
	</section>
</form>

shelfio_web/shelfio/templates/partials/new-shelf-mini.html
<form id="new-shelf" class="modal island contained-form ui-dialog-content ui-widget-content" action="" style="display: none; width: auto; min-height: 148px; height: auto;" scrolltop="0" scrollleft="0">
	<header>
		<h3>New Shelf</h3>
	</header>

	
	<section>
		<p>
			
			<label for="new_shelf_option">Shelf name</label>
			<input type="text" maxlength="200" name="name" id="new_shelf_option">
		</p>
		<p>
			
			<label for="id_description">Shelf description</label>
			<textarea name="description" cols="40" rows="4" id="id_description"></textarea>
		</p>
		<p>
			
			<label>Make shelf private <input type="checkbox" id="id_is_private" name="is_private" value="private"></label>
		</p>

		<p>
		  <a class="button neutral modal-close">Cancel</a>
			<a class="button positive icon-ok modal-submit" type="submit">Create Shelf</a>
		</p>
	</section>
</form>

shelfio_web/shelfio/templates/partials/shelf-overview.html
{% if is_owner or not shelf.is_private %}
	<article class="shelf-overview island" data-uuid="{{ shelf.shelf_uuid }}">
		<header>
			<h2><a href="{% url 'user_shelf' user_name shelf.slug %}">{{ shelf.name }}</a></h2>
			{% if is_owner %}
				<span style="float:right">
				{% if shelf.is_private %}
    				<span class="icon-lock"></span>
				{% else %}
					<span class="icon-unlock"></span>
				{% endif %}
				</span>
			{% endif %}
			</h2>
		</header>

		<section>
			{% if shelf.description  %}
				{{ shelf.description }}
			{% else %}
				(No description)
			{% endif %}
		</section>

		<footer>
			{% if is_owner %}
				<span class="shelf-date">Created on {{ shelf.creation_date|date:"F jS, Y" }}</span>	
				<span class="shelf-edit"><a href="#edit-shelf" class="button-small neutral edit-shelf icon-edit">Edit Shelf</a></span>
			{% endif %}
		</footer>
	</article>
{% endif %}

shelfio_web/shelfio/templates/partials/user-widget.html
{% load md5 %}

<figure class="profile-image">
	<img src="http://www.gravatar.com/avatar/{{ email|md5 }}?s=256&d=mm" alt="{{ user_name }}">
	<figcaption>{{ user_name }}</figcaption>
</figure>

{% if user.is_authenticated and not is_owner %}
	<a class="button neutral {% if is_favorite  %}icon-star{% else %}icon-unstar{% endif %}" href=""></a>
{% endif %}

{% if is_owner %}
	<ul class="profile-info">
		{% if first_name or last_name %}
			<li><strong>Name:</strong> {{ first_name }} {{ last_name }}</li>
		{% endif %}
		{% if email %}
			<li><strong>Email:</strong> {{ email }}</li>
		{% endif %}
		{% if user.is_authenticated %}
			<li><strong>Joined shelf.io on:</strong> {{ date_joined|date:"F jS, Y" }}</li>
		{% endif %}
		
		<li class="edit-profile"><a href="#edit-profile" class="button-small neutral icon-edit">Edit profile</a></li>
	</ul>

	<form class="contained-form island form-hidden" action="." method="post" id="edit-profile">
		<input type="hidden" name="_method" value="patch">
		{% csrf_token %}
		
		<header>
			<h3>Edit Profile</h3>
		</header>
		
		<section>
			<div class="edit-profile-section">
				<label>Change password:</label>
				<p class="profile-text">Change your password? <a href="{% url 'auth_password_change' %}">The password management page is what you want.</a></p>
			</div>
			<div class="edit-profile-section">
				<label>Change profile pic:</label>
				<p class="profile-text">Profile images are managed by <a href="http://gravatar.com" target="_blank">Gravatar</a>. Be sure your Shelf.io email matches your Gravatar email.</p>
			</div>

			{{ profileform.as_p }}
			<p>
				<button type="submit" class="button positive icon-ok">Ok</button>
			</p>
		</section>
	</form>
	
{% endif %}